// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WalletScanner.Data;

#nullable disable

namespace walletscanner.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WalletScanner.Models.Alert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ThresholdAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TokenId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("TokenId", "AlertType");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("WalletScanner.Models.DumpEvent", b =>
                {
                    b.Property<int>("DumpEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DumpEventId"));

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PriceDropPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TokenId")
                        .HasColumnType("int");

                    b.Property<decimal>("VolumeSold")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("WalletId")
                        .HasColumnType("int");

                    b.HasKey("DumpEventId");

                    b.HasIndex("TokenId");

                    b.HasIndex("WalletId");

                    b.ToTable("DumpEvents");
                });

            modelBuilder.Entity("WalletScanner.Models.Token", b =>
                {
                    b.Property<int>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TokenId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("Decimals")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Liquidity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LogoURI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MarketCap")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PriceChangePercent24h")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Volume24hUSD")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TokenId");

                    b.HasIndex("Address")
                        .IsUnique();

                    b.ToTable("Tokens");
                });

            modelBuilder.Entity("WalletScanner.Models.TokenMetric", b =>
                {
                    b.Property<int>("TokenId")
                        .HasColumnType("int");

                    b.Property<string>("CorrelationData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("TopPerformingWallets")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TokenId");

                    b.ToTable("TokenMetrics");
                });

            modelBuilder.Entity("WalletScanner.Models.TopTrader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TokenId")
                        .HasColumnType("int");

                    b.Property<int?>("TradeBuyCount")
                        .HasColumnType("int");

                    b.Property<int?>("TradeCount")
                        .HasColumnType("int");

                    b.Property<int?>("TradeSellCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Volume")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VolumeBuy")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VolumeSell")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("WalletId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TokenId");

                    b.HasIndex("WalletId");

                    b.ToTable("TopTraders");
                });

            modelBuilder.Entity("WalletScanner.Models.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("BlockNumber")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("BlockTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Fee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FromAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("ToAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TokenId")
                        .HasColumnType("int");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TxHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ValueUsd")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("WalletId")
                        .HasColumnType("int");

                    b.HasKey("TransactionId");

                    b.HasIndex("BlockTime");

                    b.HasIndex("TokenId");

                    b.HasIndex("WalletId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("WalletScanner.Models.TrendingToken", b =>
                {
                    b.Property<int>("TokenId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Rank")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Volume24hUSD")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TokenId");

                    b.ToTable("TrendingTokens");
                });

            modelBuilder.Entity("WalletScanner.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WalletScanner.Models.Wallet", b =>
                {
                    b.Property<int>("WalletId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WalletId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("TotalUsdValue")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("WalletId");

                    b.HasIndex("Address")
                        .IsUnique();

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("WalletScanner.Models.WalletHolding", b =>
                {
                    b.Property<int>("WalletId")
                        .HasColumnType("int");

                    b.Property<int>("TokenId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PriceUsd")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("UiAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ValueUsd")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("WalletId", "TokenId");

                    b.HasIndex("TokenId");

                    b.ToTable("WalletHoldings");
                });

            modelBuilder.Entity("WalletScanner.Models.WalletMetric", b =>
                {
                    b.Property<int>("WalletId")
                        .HasColumnType("int");

                    b.Property<decimal?>("AverageHoldTime")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CostBasis")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Profitability")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TradeFrequency")
                        .HasColumnType("int");

                    b.Property<decimal?>("TradeSizeAverage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("WinLossRatio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("WalletId");

                    b.ToTable("WalletMetrics");
                });

            modelBuilder.Entity("WalletScanner.Models.WhaleActivity", b =>
                {
                    b.Property<int>("WhaleActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WhaleActivityId"));

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("TokenId")
                        .HasColumnType("int");

                    b.Property<decimal>("ValueUsd")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("WalletId")
                        .HasColumnType("int");

                    b.HasKey("WhaleActivityId");

                    b.HasIndex("WalletId");

                    b.HasIndex("TokenId", "Timestamp");

                    b.ToTable("WhaleActivities");
                });

            modelBuilder.Entity("WalletScanner.Models.Alert", b =>
                {
                    b.HasOne("WalletScanner.Models.Token", "Token")
                        .WithMany()
                        .HasForeignKey("TokenId");

                    b.HasOne("WalletScanner.Models.User", "User")
                        .WithMany("Alerts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Token");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WalletScanner.Models.DumpEvent", b =>
                {
                    b.HasOne("WalletScanner.Models.Token", "Token")
                        .WithMany("DumpEvents")
                        .HasForeignKey("TokenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WalletScanner.Models.Wallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletId");

                    b.Navigation("Token");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("WalletScanner.Models.TokenMetric", b =>
                {
                    b.HasOne("WalletScanner.Models.Token", "Token")
                        .WithOne("TokenMetric")
                        .HasForeignKey("WalletScanner.Models.TokenMetric", "TokenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Token");
                });

            modelBuilder.Entity("WalletScanner.Models.TopTrader", b =>
                {
                    b.HasOne("WalletScanner.Models.Token", "Token")
                        .WithMany("TopTraders")
                        .HasForeignKey("TokenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WalletScanner.Models.Wallet", "Wallet")
                        .WithMany("TopTraders")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Token");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("WalletScanner.Models.Transaction", b =>
                {
                    b.HasOne("WalletScanner.Models.Token", "Token")
                        .WithMany("Transactions")
                        .HasForeignKey("TokenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WalletScanner.Models.Wallet", "Wallet")
                        .WithMany("Transactions")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Token");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("WalletScanner.Models.TrendingToken", b =>
                {
                    b.HasOne("WalletScanner.Models.Token", "Token")
                        .WithOne("TrendingToken")
                        .HasForeignKey("WalletScanner.Models.TrendingToken", "TokenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Token");
                });

            modelBuilder.Entity("WalletScanner.Models.WalletHolding", b =>
                {
                    b.HasOne("WalletScanner.Models.Token", "Token")
                        .WithMany("WalletHoldings")
                        .HasForeignKey("TokenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WalletScanner.Models.Wallet", "Wallet")
                        .WithMany("WalletHoldings")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Token");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("WalletScanner.Models.WalletMetric", b =>
                {
                    b.HasOne("WalletScanner.Models.Wallet", "Wallet")
                        .WithOne("WalletMetric")
                        .HasForeignKey("WalletScanner.Models.WalletMetric", "WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("WalletScanner.Models.WhaleActivity", b =>
                {
                    b.HasOne("WalletScanner.Models.Token", "Token")
                        .WithMany("WhaleActivities")
                        .HasForeignKey("TokenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WalletScanner.Models.Wallet", "Wallet")
                        .WithMany("WhaleActivities")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Token");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("WalletScanner.Models.Token", b =>
                {
                    b.Navigation("DumpEvents");

                    b.Navigation("TokenMetric")
                        .IsRequired();

                    b.Navigation("TopTraders");

                    b.Navigation("Transactions");

                    b.Navigation("TrendingToken")
                        .IsRequired();

                    b.Navigation("WalletHoldings");

                    b.Navigation("WhaleActivities");
                });

            modelBuilder.Entity("WalletScanner.Models.User", b =>
                {
                    b.Navigation("Alerts");
                });

            modelBuilder.Entity("WalletScanner.Models.Wallet", b =>
                {
                    b.Navigation("TopTraders");

                    b.Navigation("Transactions");

                    b.Navigation("WalletHoldings");

                    b.Navigation("WalletMetric")
                        .IsRequired();

                    b.Navigation("WhaleActivities");
                });
#pragma warning restore 612, 618
        }
    }
}
